name: Build JUCE Project

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Linux dependencies
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev

            - name: Configure CMake
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    cmake --preset=vs2022 -B build
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    cmake -B build -G Xcode
                  else
                    cmake -B build
                  fi

            - name: Build with CMake
              run: cmake --build build --config Release

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Simple-JUCE-App-${{ matrix.os }}
                  path: |
                      build/SimpleJuceApp_artefacts/Release/
                      !build/SimpleJuceApp_artefacts/Release/*.pdb
