name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  lint:
    name: Lint Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run markdown linting
      run: npm test

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v5

    - name: Set build environment variables
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          # On Windows, always use vs2022 preset regardless of build type
          echo "CMAKE_PRESET=vs2022" >> $GITHUB_ENV
          echo "BUILD_DIR=${{github.workspace}}/build/vs2022" >> $GITHUB_ENV
        else
          # On non-Windows platforms, use preset based on build type
          if [ "${{matrix.build_type}}" == "Release" ]; then
            echo "CMAKE_PRESET=release" >> $GITHUB_ENV
            echo "BUILD_DIR=${{github.workspace}}/build/release" >> $GITHUB_ENV
          else
            echo "CMAKE_PRESET=default" >> $GITHUB_ENV
            echo "BUILD_DIR=${{github.workspace}}/build" >> $GITHUB_ENV
          fi
        fi
      shell: bash

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxrandr-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libgl1-mesa-dev \
          libxext-dev \
          libcurl4-openssl-dev \
          libwebkit2gtk-4.1-dev \
          pkg-config \
          build-essential

    - name: Configure CMake
      run: cmake --preset=${{ env.CMAKE_PRESET }}
      shell: bash

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{matrix.build_type}}
      shell: bash

    - name: Test (Linux/macOS)
      if: runner.os != 'Windows'
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        # Check standalone binary path (differs between Linux and macOS)
        if [ "$RUNNER_OS" == "macOS" ]; then
          # macOS creates app bundle
          if [ -d "DSPJucePlugin_artefacts/${{matrix.build_type}}/Standalone/DSP-JUCE Plugin.app" ]; then
            echo "✅ Build successful - macOS app bundle created"
          else
            echo "❌ Build failed - macOS app bundle not found"
            ls -la DSPJucePlugin_artefacts/${{matrix.build_type}}/Standalone/
            exit 1
          fi
        else
          # Linux creates executable
          if [ -f "DSPJucePlugin_artefacts/${{matrix.build_type}}/Standalone/DSP-JUCE Plugin" ]; then
            echo "✅ Build successful - Linux binary created"
          else
            echo "❌ Build failed - Linux binary not found"
            ls -la DSPJucePlugin_artefacts/${{matrix.build_type}}/Standalone/
            exit 1
          fi
        fi

    - name: Test (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        # For now, just verify the binary was created
        if (Test-Path "DSPJucePlugin_artefacts/${{matrix.build_type}}/Standalone/DSP-JUCE Plugin.exe") {
          Write-Host "✅ Build successful - binary created"
        } else {
          Write-Host "❌ Build failed - binary not found"
          Get-ChildItem DSPJucePlugin_artefacts/${{matrix.build_type}}/
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.build_type == 'Release'
      with:
        name: DSPJucePlugin-${{ matrix.os }}
        path: ${{ env.BUILD_DIR }}/DSPJucePlugin_artefacts/Release/
        retention-days: 30